# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: md5

    providers:
        fos_userbundle:
              id: fos_user.user_manager

    role_hierarchy:
          ROLE_ADMIN:
              - ROLE_USER
              - ROLE_SONATA_ADMIN
              # USER
              - ROLE_ADMIN_USER_CREATE
              - ROLE_ADMIN_USER_DELETE
              - ROLE_ADMIN_USER_EDIT
              - ROLE_ADMIN_USER_LIST
              - ROLE_ADMIN_USER_VIEW
              - ROLE_ADMIN_USER_EXPORT
              - ROLE_ADMIN_USER_OPERATOR
              - ROLE_ADMIN_USER_MASTER
              # VEHICLE
              - ROLE_ADMIN_VEHICLE_CREATE
              - ROLE_ADMIN_VEHICLE_DELETE
              - ROLE_ADMIN_VEHICLE_EDIT
              - ROLE_ADMIN_VEHICLE_LIST
              - ROLE_ADMIN_VEHICLE_VIEW
              - ROLE_ADMIN_VEHICLE_EXPORT
              - ROLE_ADMIN_VEHICLE_OPERATOR
              - ROLE_ADMIN_VEHICLE_MASTER
          ROLE_SUPER_ADMIN:
              - ROLE_ADMIN
              - ROLE_ALLOWED_TO_SWITCH
          SONATA:
              - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT

    access_decision_manager:
            strategy: unanimous

    access_control:
            # URL of FOSUserBundle which need to be available to anonymous users
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

            # Admin login page needs to be accessed without credential
            - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

            # Secured part of the site
            # This config requires being logged for the whole site and having the admin role for the admin part.
            # Change these rules to adapt them to your needs
            - { path: ^/admin/, role: [ROLE_ADMIN] }
            - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
                default_target_path: /admin/dashboard
            logout:
                path:           /admin/logout
                target:         /admin/login
            anonymous:          ~
        #api:
          #pattern:   ^/api/v1
          #stateless: true
          #lexik_jwt:
              #authorization_header:
                     #enabled: true
                     #prefix:  Bearer
                     #name:    Authorization
              #throw_exceptions: false